from talib import abstract
from custom_functions import adx_system, adxr_system, efi, mayermultiple, networkvalue2transactions,\
    networkvalue2transactionsignal, donchianchannel, bollinger_band_bands, fibonacci_extensions, fibonacci_reversal,\
    pivotpoints, ichimoku_clouds, hullma, zerolagexponentialmovingaverage, williamsalligatorpyti


# For the custom plots template
top_bottom_functions = {'ADX':['Average Directional Index (ADX)',adx_system,['blue','green','red']],
                      'ADXR':['Average Directional Movement Rating (ADXR)',adxr_system, ['blue','green','red']],
                      'APO':['Absolute Price Oscillator (APO)',abstract.APO, None],
                      'AROON':['Aroon Indicator (AROON)',abstract.AROON, ['red','green']],
                      'AROONOSC':['Aroon Oscillator (AROONOSC)',abstract.AROONOSC, None],
                      'ATR':['Average True Range (ATR)',abstract.ATR, None],
                      'BOP':['Balance of Power (BOP)',abstract.BOP, None],
                      'CCI':['Commodity Channel Index (CCI)',abstract.CCI, None],
                      'CMO':['Chande Momentum Oscillator (CMO)',abstract.CMO, None],
                      'DX':['Directional Movement Index (DX)',abstract.DX, None],
                      'EFI':['Elder Force Index (EFI)',efi, None],
                      'MM':['Mayer Multiple (MM)',mayermultiple, None],
                      'MACD':['Moving Average Convergence Divergence (MACD)',abstract.MACD,['blue','gold','red']],
                      'MFI':['Money Flow Index (MFI)',abstract.MFI, None],
                      'MINUS_DI':['Minus Directional Indicator (MINUS_DI)',abstract.MINUS_DI, None],
                      'MINUS_DM':['Minus Directional Movement (MINUS_DM)',abstract.MINUS_DM, None],
                      'MOM':['Momentum (MOM)',abstract.MOM, None],
                      'NVTR':['Network Value to Transaction Ratio (NVTR)', networkvalue2transactions, None],
                      'NVTS':['Network Value to Transaction Signal (NVTS)', networkvalue2transactionsignal, None],
                      'PLUS_DI':['Plus Directional Indicator (PLUS_DI)',abstract.PLUS_DI, None],
                      'PLUS_DM':['Plus Directional Movement (PLUS_DM)',abstract.PLUS_DM, None],
                      'PPO':['Percentage Price Oscillator (PPO)',abstract.PPO, None],
                      'ROC':['Rate of Change (ROC)',abstract.ROC, None],
                      'ROCP':['Rate of change Percentage (ROCP)',abstract.ROCP, None],
                      'ROCR':['Rate of change ratio (ROCR)',abstract.ROCR, None],
                      'ROCR100':['Rate of change ratio 100 scale (ROCR100)',abstract.ROCR100, None],
                      'RSI':['Relative Strength Index (RSI)',abstract.RSI, None],
                      'STOCH':['Stochastic Oscillator (STOCH)',abstract.STOCH, ['blue','gold']],
                      'STOCHF':['Stochastic Fast (STOCHF)',abstract.STOCHF,['blue','gold']],
                      'STOCHRSI':['Stochastic Relative Strength Index (STOCHRSI)',abstract.STOCHRSI,['blue','gold']],
                      'TRIX':['Triple Exponential Average (TRIX)',abstract.TRIX, None],
                      'ULTOSC':['Ultimate Oscillator (ULTOSC)',abstract.ULTOSC, None],
                      'WILLR':['Williams Percent Range (WILLR)',abstract.WILLR, None]}


main_plot_functions = {'OBV': ['On Balance Volume (OBV)', abstract.OBV, None],
                       'BB': ['Bollinger Bands (BB)', abstract.BBANDS, ['lightcoral','aquamarine','chartreuse']],
                       'DCHAN': ['Donchian Channel (DCHAN)', donchianchannel, ['lightcoral','chartreuse','aquamarine']],
                       'BBB': ['Bollinger Band Bands (BBB)', bollinger_band_bands, ['chartreuse','lightcoral','green','red']],
                       'PIV': ['Pivot Points (PIV)', pivotpoints, ['blue','red','red','red','green','green','green']],
                       'ICH': ['Ichimoku Clouds (ICH)', ichimoku_clouds, ['blue','goldenrod','springgreen','coral','silver']],
                       'Alligator': ['Williams Alligator Indicator (Alligator)', williamsalligatorpyti,
                                     ['blue', 'red', 'green']]

                       }

moving_Averages = {'SMA':['Simple Moving Average (SMA)', abstract.SMA],
                   'EMA':['Exponential Moving Average (EMA)', abstract.EMA],
                   'WMA':['Weighted Moving Average (WMA)', abstract.WMA],
                   'DEMA':['Double Exponential Moving Average (DEMA)', abstract.DEMA],
                   'T3': ['Triple Exponential Moving Average (T3)', abstract.T3],
                   'TEMA':['Triple Exponential Moving Average (TEMA)', abstract.TEMA],
                   'TRIMA':['Triangular Moving Average (TRIMA)', abstract.TRIMA],
                   'KAMA': ['Kaufman Adaptive Moving Average (KAMA)', abstract.KAMA],
                   'HMA': ['Hull Moving Average (HMA)', hullma],
                   'ZLEMA': ['Zero-lag Exponential Moving Average (ZLEMA)', zerolagexponentialmovingaverage]
                    }

fibonaccis = {'FIBEXT': ['Fibonacci Extension Levels (FIBEXT)', fibonacci_extensions,
                         ['lightsalmon','palegoldenrod','palegreen','powderblue',
                          'pink','purple','blue'],
                         ['lv1','lv2','lv3','lv4','lv5','lv6','lv7']
                         ],

              'FIBRET': ['Fibonacci Reversal Levels (FIBRET)', fibonacci_reversal,
                         ['red', 'red', 'red', 'green', 'green', 'green', 'blue'],
                         ['Resistance', None, None, 'Support', None, None, 'Baseline']
                         ]
              }


pattern_functions = {'CDL2CROWS':['Two Crows (CDL2CROWS)', abstract.CDL2CROWS],
                     'CDL3BLACKCROWS':['Three Black Crows (CDL3BLACKCROWS)', abstract.CDL3BLACKCROWS],
                     'CDL3INSIDE':['Three Inside Up/Down (CDL3INSIDE)', abstract.CDL3INSIDE],
                     'CDL3LINESTRIKE':['Three-Line Strike (CDL3LINESTRIKE)', abstract.CDL3LINESTRIKE],
                     'CDL3OUTSIDE':['Three Outside Up/Down (CDL3OUTSIDE)',abstract.CDL3OUTSIDE],
                     'CDL3STARSINSOUTH':['Three Stars In The South (CDL3STARSINSOUTH)', abstract.CDL3STARSINSOUTH],
                     'CDL3WHITESOLDIERS':['Three Advancing White Soldiers (CDL3WHITESOLDIERS)', abstract.CDL3WHITESOLDIERS],
                     'CDLABANDONEDBABY': ['Abandoned Baby (CDLABANDONEDBABY)', abstract.CDLABANDONEDBABY],
                     'CDLADVANCEBLOCK': ['Advance Block (CDLADVANCEBLOCK)', abstract.CDLADVANCEBLOCK],
                     'CDLBELTHOLD':['Belt-hold (CDLBELTHOLD)', abstract.CDLBELTHOLD],
                     'CDLBREAKAWAY':['Breakaway (CDLBREAKAWAY)', abstract.CDLBREAKAWAY],
                     'CDLCLOSINGMARUBOZU':['Closing Marubozu (CDLCLOSINGMARUBOZU)', abstract.CDLCLOSINGMARUBOZU],
                     'CDLCONCEALBABYSWALL': ['Concealing Baby Swallow (CDLCONCEALBABYSWALL)', abstract.CDLCONCEALBABYSWALL],
                     'CDLCOUNTERATTACK':['Counterattack (CDLCOUNTERATTACK)', abstract.CDLCOUNTERATTACK],
                     'CDLDARKCLOUDCOVER':['Dark Cloud Cover (CDLDARKCLOUDCOVER)', abstract.CDLDARKCLOUDCOVER],
                     'CDLDOJI':['Doji (CDLDOJI)', abstract.CDLDOJI],
                     'CDLDOJISTAR':['Doji Star (CDLDOJISTAR)', abstract.CDLDOJISTAR],
                     'CDLDRAGONFLYDOJI':['Dragonfly Doji (CDLDRAGONFLYDOJI)', abstract.CDLDRAGONFLYDOJI],
                     'CDLENGULFING': ['Engulfing Pattern (CDLENGULFING)', abstract.CDLENGULFING],
                     'CDLEVENINGDOJISTAR': ['Evening Doji Star (CDLEVENINGDOJISTAR)', abstract.CDLEVENINGDOJISTAR],
                     'CDLEVENINGSTAR': ['Evening Star (CDLEVENINGSTAR)', abstract.CDLEVENINGSTAR],
                     'CDLGAPSIDESIDEWHITE':['Up/Down-gap side-by-side white lines (CDLGAPSIDESIDEWHITE)', abstract.CDLGAPSIDESIDEWHITE],
                     'CDLGRAVESTONEDOJI': ['Gravestone Doji (CDLGRAVESTONEDOJI)', abstract.CDLGRAVESTONEDOJI],
                     'CDLHAMMER':['Hammer (CDLHAMMER)', abstract.CDLHAMMER],
                     'CDLHANGINGMAN':['Hanging Man (CDLHANGINGMAN)', abstract.CDLHANGINGMAN],
                     'CDLHARAMI':['Harami Pattern (CDLHARAMI)', abstract.CDLHARAMI],
                     'CDLHARAMICROSS':['Harami Cross Pattern (CDLHARAMICROSS)', abstract.CDLHARAMICROSS],
                     'CDLHIGHWAVE':['High-Wave Candle (CDLHIGHWAVE)', abstract.CDLHIGHWAVE],
                     'CDLHIKKAKE': ['Hikkake Pattern (CDLHIKKAKE)', abstract.CDLHIKKAKE],
                     'CDLHIKKAKEMOD': ['Modified Hikkake Pattern (CDLHIKKAKEMOD)', abstract.CDLHIKKAKEMOD],
                     'CDLHOMINGPIGEON':['Homing Pigeon (CDLHOMINGPIGEON)', abstract.CDLHOMINGPIGEON],
                     'CDLIDENTICAL3CROWS': ['Identical Three Crows (CDLIDENTICAL3CROWS)', abstract.CDLIDENTICAL3CROWS],
                     'CDLINNECK': ['In-Neck Pattern (CDLINNECK)', abstract.CDLINNECK],
                     'CDLINVERTEDHAMMER':['Inverted Hammer (CDLINVERTEDHAMMER)', abstract.CDLINVERTEDHAMMER],
                     'CDLKICKING':['Kicking (CDLKICKING)', abstract.CDLKICKING],
                     'CDLKICKINGBYLENGTH': ['Kicking - bull/bear determined by the longer marubozu (CDLKICKINGBYLENGTH)', abstract.CDLKICKINGBYLENGTH],
                     'CDLLADDERBOTTOM': ['Ladder Bottom (CDLLADDERBOTTOM)', abstract.CDLLADDERBOTTOM],
                     'CDLLONGLEGGEDDOJI': ['Long Legged Doji (CDLLONGLEGGEDDOJI)', abstract.CDLLONGLEGGEDDOJI],
                     'CDLLONGLINE':['Long Line Candle (CDLLONGLINE)', abstract.CDLLONGLINE],
                     'CDLMARUBOZU':['Marubozu (CDLMARUBOZU)', abstract.CDLMARUBOZU],
                     'CDLMATCHINGLOW': ['Matching Low (CDLMATCHINGLOW)', abstract.CDLMATCHINGLOW],
                     'CDLMATHOLD': ['Mat Hold (CDLMATHOLD)', abstract.CDLMATHOLD],
                     'CDLMORNINGDOJISTAR': ['Morning Doji Star (CDLMORNINGDOJISTAR)', abstract.CDLMORNINGDOJISTAR],
                     'CDLMORNINGSTAR':['Morning Star(CDLMORNINGSTAR)', abstract.CDLMORNINGSTAR],
                     'CDLONNECK':['On-Neck Pattern (CDLONNECK)', abstract.CDLONNECK],
                     'CDLPIERCING': ['Piercing Pattern (CDLPIERCING)', abstract.CDLPIERCING],
                     'CDLRICKSHAWMAN': ['Rickshaw Man (CDLRICKSHAWMAN)', abstract.CDLRICKSHAWMAN],
                     'CDLRISEFALL3METHODS': ['Rising/Falling Three Methods (CDLRISEFALL3METHODS)', abstract.CDLRISEFALL3METHODS],
                     'CDLSEPARATINGLINES': ['Separating Lines (CDLSEPARATINGLINES)', abstract.CDLSEPARATINGLINES],
                     'CDLSHOOTINGSTAR': ['Shooting Star (CDLSHOOTINGSTAR)', abstract.CDLSHOOTINGSTAR],
                     'CDLSHORTLINE': ['Short Line Candle (CDLSHORTLINE)', abstract.CDLSHORTLINE],
                     'CDLSPINNINGTOP': ['Spinning Top (CDLSPINNINGTOP)', abstract.CDLSPINNINGTOP],
                     'CDLSTALLEDPATTERN':['Stalled Pattern (CDLSTALLEDPATTERN)', abstract.CDLSTALLEDPATTERN],
                     'CDLSTICKSANDWICH':['Stick Sandwich (CDLSTICKSANDWICH)', abstract.CDLSTICKSANDWICH],
                     'CDLTAKURI':['Takuri (Dragonfly Doji with very long lower shadow) (CDLTAKURI)', abstract.CDLTAKURI],
                     'CDLTASUKIGAP': ['Tasuki Gap (CDLTASUKIGAP)', abstract.CDLTASUKIGAP],
                     'CDLTHRUSTING':['Thrusting Pattern (CDLTHRUSTING)', abstract.CDLTHRUSTING],
                     'CDLTRISTAR':['Tristar Pattern (CDLTRISTAR)', abstract.CDLTRISTAR],
                     'CDLUNIQUE3RIVER':['Unique 3 River (CDLUNIQUE3RIVER)', abstract.CDLUNIQUE3RIVER],
                     'CDLUPSIDEGAP2CROWS': ['Upside Gap Two Crows (CDLUPSIDEGAP2CROWS)', abstract.CDLUPSIDEGAP2CROWS],
                     'CDLXSIDEGAP3METHODS':['Upside/Downside Gap Three Methods (CDLXSIDEGAP3METHODS)', abstract.CDLXSIDEGAP3METHODS]
                     }

timeframes = {
    '1m': 'One Month (30 days)',
    '3m': 'Three Months (90 days)',
    '6m': 'Six Months (180 days)',
    '1y': 'One Year (360 days)',
    '2y': 'Two Years (720 days)',
    '3y': 'Three Years (1080 days)',
    'Max': 'All available data (1800 days)',

}

# For the indicator signals template
abstract_functions = {
                      'ADXS' : 'Average Directional Index System (ADXS)',
                      'APO': 'Absolute Price Oscillator (APO)',
                      'AROONI25': 'Aroon Indicator 25 (AROON 25)',
                      'AROONI75': 'Aroon Indicator 75 (AROON 75)',
                      'AROONO25': 'Aroon Oscillator 25 (AROONOSC 25)',
                      'AROONO75': 'Aroon Oscillator 75 (AROONOSC 75)',
                      'BOP': 'Balance of Power (BOP)',
                      'BOP14': 'Balance of Power 14 (BOP14)',
                      'CCI': 'Commodity Channel Index (CCI) 14',
                      'CCI20': 'Commodity Channel Index (CCI) 20',
                      'CCI40': 'Commodity Channel Index (CCI) 40',
                      'CMO14': 'Chande Momentum Oscillator (CMO 14)',
                      'CMO20': 'Chande Momentum Oscillator (CMO 20)',
                      'EFI2': 'Elder Force Index Fast (EFI 2)',
                      'EFI13': 'Elder Force Index Fast (EFI 13)',
                      'EFI30': 'Elder Force Index Fast (EFI 30)',
                      'EFI100': 'Elder Force Index Slow (EFI 100)',
                      'MM': 'Mayer Multiple (MM)',
                      'MACD': 'Moving Average Convergence Divergence (MACD)',
                      'MACDFIX': 'Moving Average Convergence/Divergence Fix 12/26 (MACDFIX)',
                      'MFI': 'Money Flow Index (MFI)',
                      'MOM': 'Momentum (MOM)',
                      'MOM9': 'Momentum 9 (MOM9)',
                      'MOM14': 'Momentum 14 (MOM14)',
                      'MOM21': 'Momentum 21 (MOM21)',
                      'PPO': 'Percentage Price Oscillator (PPO)',
                      'PPOS': 'Percentage Price Oscillator Signal (PPOS)',
                      'PPOSL': 'Percentage Price Oscillator Signal Long (PPOSL)',
                      'RSI': 'Relative Strength Index (RSI (14)',
                      'RSI20': 'Relative Strength Index (RSI (20))',
                      'STOCH': 'Stochastic Oscillator (5,3,3)',
                      'STOCH_MID': 'Stochastic Oscillator (21,7,7)',
                      'STOCH_LONG': 'Stochastic Oscillator (21,14,14)',
                      'STOCHF': 'Stochastic Fast (5,3)',
                      'STOCHF_MID': 'Stochastic Fast (21,7)',
                      'STOCHF_LONG': 'Stochastic Fast (21,14)',
                      'STOCHRSI': 'Stochastic Relative Strength Index (STOCHRSI (14))',
                      'STOCHRSI20': 'Stochastic Relative Strength Index (STOCHRSI (20))',
                      'WILLR': 'Williams Percent Range (WILLR)',
                      }


# For the pattern signals template
pattern_signals = {'CDL2CROWS':  'Two Crows (CDL2CROWS)',
                     'CDL3BLACKCROWS':  'Three Black Crows (CDL3BLACKCROWS)',
                     'CDL3INSIDE':  'Three Inside Up/Down (CDL3INSIDE)',
                     'CDL3LINESTRIKE':  'Three-Line Strike (CDL3LINESTRIKE)',
                     'CDL3OUTSIDE':  'Three Outside Up/Down (CDL3OUTSIDE)',
                     'CDL3STARSINSOUTH':  'Three Stars In The South (CDL3STARSINSOUTH)',
                     'CDL3WHITESOLDIERS':  'Three Advancing White Soldiers (CDL3WHITESOLDIERS)',
                     'CDLABANDONEDBABY':   'Abandoned Baby (CDLABANDONEDBABY)',
                     'CDLADVANCEBLOCK':   'Advance Block (CDLADVANCEBLOCK)',
                     'CDLBELTHOLD':  'Belt-hold (CDLBELTHOLD)',
                     'CDLBREAKAWAY':  'Breakaway (CDLBREAKAWAY)',
                     'CDLCLOSINGMARUBOZU':  'Closing Marubozu (CDLCLOSINGMARUBOZU)',
                     'CDLCONCEALBABYSWALL':   'Concealing Baby Swallow (CDLCONCEALBABYSWALL)',
                     'CDLCOUNTERATTACK':  'Counterattack (CDLCOUNTERATTACK)',
                     'CDLDARKCLOUDCOVER':  'Dark Cloud Cover (CDLDARKCLOUDCOVER)',
                     'CDLDOJI':  'Doji (CDLDOJI)',
                     'CDLDOJISTAR':  'Doji Star (CDLDOJISTAR)',
                     'CDLDRAGONFLYDOJI':  'Dragonfly Doji (CDLDRAGONFLYDOJI)',
                     'CDLENGULFING':   'Engulfing Pattern (CDLENGULFING)',
                     'CDLEVENINGDOJISTAR':   'Evening Doji Star (CDLEVENINGDOJISTAR)',
                     'CDLEVENINGSTAR':   'Evening Star (CDLEVENINGSTAR)',
                     'CDLGAPSIDESIDEWHITE':  'Up/Down-gap side-by-side white lines (CDLGAPSIDESIDEWHITE)',
                     'CDLGRAVESTONEDOJI':   'Gravestone Doji (CDLGRAVESTONEDOJI)',
                     'CDLHAMMER':  'Hammer (CDLHAMMER)',
                     'CDLHANGINGMAN':  'Hanging Man (CDLHANGINGMAN)',
                     'CDLHARAMI':  'Harami Pattern (CDLHARAMI)',
                     'CDLHARAMICROSS':  'Harami Cross Pattern (CDLHARAMICROSS)',
                     'CDLHIGHWAVE':  'High-Wave Candle (CDLHIGHWAVE)',
                     'CDLHIKKAKE':   'Hikkake Pattern (CDLHIKKAKE)',
                     'CDLHIKKAKEMOD':   'Modified Hikkake Pattern (CDLHIKKAKEMOD)',
                     'CDLHOMINGPIGEON':  'Homing Pigeon (CDLHOMINGPIGEON)',
                     'CDLIDENTICAL3CROWS':   'Identical Three Crows (CDLIDENTICAL3CROWS)',
                     'CDLINNECK':   'In-Neck Pattern (CDLINNECK)',
                     'CDLINVERTEDHAMMER':  'Inverted Hammer (CDLINVERTEDHAMMER)',
                     'CDLKICKING':  'Kicking (CDLKICKING)',
                     'CDLKICKINGBYLENGTH':   'Kicking - bull/bear determined by the longer marubozu (CDLKICKINGBYLENGTH)',
                     'CDLLADDERBOTTOM':   'Ladder Bottom (CDLLADDERBOTTOM)',
                     'CDLLONGLEGGEDDOJI':   'Long Legged Doji (CDLLONGLEGGEDDOJI)',
                     'CDLLONGLINE':  'Long Line Candle (CDLLONGLINE)',
                     'CDLMARUBOZU':  'Marubozu (CDLMARUBOZU)',
                     'CDLMATCHINGLOW':   'Matching Low (CDLMATCHINGLOW)',
                     'CDLMATHOLD':   'Mat Hold (CDLMATHOLD)',
                     'CDLMORNINGDOJISTAR':   'Morning Doji Star (CDLMORNINGDOJISTAR)',
                     'CDLMORNINGSTAR':  'Morning Star(CDLMORNINGSTAR)',
                     'CDLONNECK':  'On-Neck Pattern (CDLONNECK)',
                     'CDLPIERCING':   'Piercing Pattern (CDLPIERCING)',
                     'CDLRICKSHAWMAN':   'Rickshaw Man (CDLRICKSHAWMAN)',
                     'CDLRISEFALL3METHODS':   'Rising/Falling Three Methods (CDLRISEFALL3METHODS)',
                     'CDLSEPARATINGLINES':   'Separating Lines (CDLSEPARATINGLINES)',
                     'CDLSHOOTINGSTAR':   'Shooting Star (CDLSHOOTINGSTAR)',
                     'CDLSHORTLINE':   'Short Line Candle (CDLSHORTLINE)',
                     'CDLSPINNINGTOP':   'Spinning Top (CDLSPINNINGTOP)',
                     'CDLSTALLEDPATTERN':  'Stalled Pattern (CDLSTALLEDPATTERN)',
                     'CDLSTICKSANDWICH':  'Stick Sandwich (CDLSTICKSANDWICH)',
                     'CDLTAKURI':  'Takuri (Dragonfly Doji with very long lower shadow) (CDLTAKURI)',
                     'CDLTASUKIGAP':   'Tasuki Gap (CDLTASUKIGAP)',
                     'CDLTHRUSTING':  'Thrusting Pattern (CDLTHRUSTING)',
                     'CDLTRISTAR':  'Tristar Pattern (CDLTRISTAR)',
                     'CDLUNIQUE3RIVER':  'Unique 3 River (CDLUNIQUE3RIVER)',
                     'CDLUPSIDEGAP2CROWS':   'Upside Gap Two Crows (CDLUPSIDEGAP2CROWS)',
                     'CDLXSIDEGAP3METHODS':  'Upside/Downside Gap Three Methods (CDLXSIDEGAP3METHODS)',
                     }


# These patterns don't return -100 values. Only 100 and 0.
pattern_filter = ['CDL3BLACKCROWS', 'CDL3STARSINSOUTH', 'CDL3WHITESOLDIERS', 'CDLABANDONEDBABY', 'CDLBREAKAWAY',
                  'CDLCONCEALBABYSWALL', 'CDLCOUNTERATTACK', 'CDLDARKCLOUDCOVER', 'CDLDOJI', 'CDLDRAGONFLYDOJI',
                  'CDLGAPSIDESIDEWHITE', 'CDLGRAVESTONEDOJI', 'CDLHAMMER', 'CDLHOMINGPIGEON', 'CDLIDENTICAL3CROWS',
                  'CDLINNECK', 'CDLINVERTEDHAMMER', 'CDLKICKING', 'CDLKICKINGBYLENGTH', 'CDLLADDERBOTTOM',
                  'CDLLONGLEGGEDDOJI', 'CDLMATCHINGLOW', 'CDLMATHOLD', 'CDLMORNINGDOJISTAR', 'CDLMORNINGSTAR',
                  'CDLONNECK', 'CDLPIERCING', 'CDLRICKSHAWMAN', 'CDLRISEFALL3METHODS', 'CDLSTICKSANDWICH', 'CDLTAKURI',
                  'CDLTASUKIGAP', 'CDLTHRUSTING', 'CDLUNIQUE3RIVER']
